### ISSUE TITLE
Any desire to co-ordinate with SimpleCov?

### ISSUE THREAD

**Issue by bf4** [seattlerb/minitest-coverage#1]
(Asking as a [maintainer](https://github.com/colszowka/simplecov/))

**Comment by zenspider** [comment]
I'll ping @sferik when I'm ready to start integration.

**Comment by bf4** [comment]
That's awfully specific, but ok `¯\_(ツ)_/¯`

**Comment by bf4** [comment]
@zenspider I guess this is closed in part because SimpleCov is compatible to 1.8 and minitest-coverage requires patches or super recent-Ruby? Still, could be useful not to create yet another library, especially when SimpleCov is so well-used and this is so similar.  (Yes, I read the code).

**Comment by zenspider** [comment]
It's closed because I said I'd reach out to Erik (or Christoph) when I'm ready to start integration.
